### ISSUE TITLE
[Doc] Use pip3 instead of pip in instructions

### ISSUE THREAD

**Issue by Nabav** [suoto/hdl_checker#95]
While following the installation guide, I got errors using `pip` which was resolved by using `pip3`. I would like to suggest fixing this in `README.md`, if it is appropriate.

* Python version used:
  * `2.7.16` (Failed)
  * `3.7.3` (Passed)
* OS: Debian 10

Log using `pip`:

```text
% pip install hdl-checker --upgrade --user
Collecting hdl-checker
  Using cached https://files.pythonhosted.org/packages/9c/45/abe3e41c1b03123dbc575c3cd7372fd78edf909454bb49af81593b2d6ca5/hdl_checker-0.7.4.tar.gz
Collecting argcomplete (from hdl-checker)
  Using cached https://files.pythonhosted.org/packages/b7/9e/9dc74d330c07866d72f62d553fe8bdbe32786ff247a14e68b5659963e6bd/argcomplete-1.12.3-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: argparse in /usr/lib/python2.7 (from hdl-checker) (1.2.1)
Collecting bottle>=0.12.9 (from hdl-checker)
  Using cached https://files.pythonhosted.org/packages/ea/80/3d2dca1562ffa1929017c74635b4cb3645a352588de89e90d0bb53af3317/bottle-0.12.19.tar.gz
Requirement already satisfied, skipping upgrade: future>=0.14.0 in /usr/lib/python2.7/dist-packages (from hdl-checker) (0.16.0)
Collecting prettytable>=0.7.2 (from hdl-checker)
  Using cached https://files.pythonhosted.org/packages/39/da/8336296a830caa495a25304e12ffb32a8c3a9d2d08ba995f066fe16152e1/prettytable-1.0.1-py2.py3-none-any.whl
Collecting pygls==0.9.1 (from hdl-checker)
  Using cached https://files.pythonhosted.org/packages/55/d9/8386d331bcd5a6d0aea45e8c9185f2d8b5403a145692d9377c9fc094d7fb/pygls-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    ('packages:', ['pygls'])
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WnEK5V/pygls/setup.py", line 36, in <module>
        with open(os.path.join(package_root_dir, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

Log using `pip3`:

```text
% pip3 install hdl-checker --upgrade --user
...
Successfully built hdl-checker
Installing collected packages: argparse, bottle, future, typing-extensions, zipp, importlib-metadata, prettytable, pygls, tabulate, typing, waitress, hdl-checker
Successfully installed argparse-1.4.0 bottle-0.12.19 future-0.18.2 hdl-checker-0.7.4 importlib-metadata-4.6.4 prettytable-2.1.0 pygls-0.9.1 tabulate-0.8.9 typing-3.7.4.3 typing-extensions-3.10.0.0 waitress-2.0.0 zipp-3.5.0
```

**Comment by suoto** [comment]
I think it's a fair change, thanks. Even though Python 2.7 has been discontinued, it's still very common to find it installed. In a system where only Python 3 is installed, then `python` and `pip` commands will point to Python 3 as expected.
